/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ParQRouteImport } from './routes/par-q'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RutinaIndexRouteImport } from './routes/rutina.index'
import { Route as RutinaDayIdRouteImport } from './routes/rutina.$dayId'

const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ParQRoute = ParQRouteImport.update({
  id: '/par-q',
  path: '/par-q',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RutinaIndexRoute = RutinaIndexRouteImport.update({
  id: '/rutina/',
  path: '/rutina/',
  getParentRoute: () => rootRouteImport,
} as any)
const RutinaDayIdRoute = RutinaDayIdRouteImport.update({
  id: '/rutina/$dayId',
  path: '/rutina/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/par-q': typeof ParQRoute
  '/perfil': typeof PerfilRoute
  '/progreso': typeof ProgresoRoute
  '/rutina/$dayId': typeof RutinaDayIdRoute
  '/rutina/': typeof RutinaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/par-q': typeof ParQRoute
  '/perfil': typeof PerfilRoute
  '/progreso': typeof ProgresoRoute
  '/rutina/$dayId': typeof RutinaDayIdRoute
  '/rutina': typeof RutinaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/par-q': typeof ParQRoute
  '/perfil': typeof PerfilRoute
  '/progreso': typeof ProgresoRoute
  '/rutina/$dayId': typeof RutinaDayIdRoute
  '/rutina/': typeof RutinaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/par-q'
    | '/perfil'
    | '/progreso'
    | '/rutina/$dayId'
    | '/rutina/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/par-q' | '/perfil' | '/progreso' | '/rutina/$dayId' | '/rutina'
  id:
    | '__root__'
    | '/'
    | '/par-q'
    | '/perfil'
    | '/progreso'
    | '/rutina/$dayId'
    | '/rutina/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParQRoute: typeof ParQRoute
  PerfilRoute: typeof PerfilRoute
  ProgresoRoute: typeof ProgresoRoute
  RutinaDayIdRoute: typeof RutinaDayIdRoute
  RutinaIndexRoute: typeof RutinaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/par-q': {
      id: '/par-q'
      path: '/par-q'
      fullPath: '/par-q'
      preLoaderRoute: typeof ParQRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutina/': {
      id: '/rutina/'
      path: '/rutina'
      fullPath: '/rutina/'
      preLoaderRoute: typeof RutinaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutina/$dayId': {
      id: '/rutina/$dayId'
      path: '/rutina/$dayId'
      fullPath: '/rutina/$dayId'
      preLoaderRoute: typeof RutinaDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParQRoute: ParQRoute,
  PerfilRoute: PerfilRoute,
  ProgresoRoute: ProgresoRoute,
  RutinaDayIdRoute: RutinaDayIdRoute,
  RutinaIndexRoute: RutinaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
