/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as ParQRouteImport } from './routes/par-q'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RutinaIndexRouteImport } from './routes/rutina.index'
import { Route as RutinaDayIdRouteImport } from './routes/rutina.$dayId'
import { Route as PerfilUserIdRouteImport } from './routes/perfil.$userId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const ParQRoute = ParQRouteImport.update({
  id: '/par-q',
  path: '/par-q',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RutinaIndexRoute = RutinaIndexRouteImport.update({
  id: '/rutina/',
  path: '/rutina/',
  getParentRoute: () => rootRouteImport,
} as any)
const RutinaDayIdRoute = RutinaDayIdRouteImport.update({
  id: '/rutina/$dayId',
  path: '/rutina/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilUserIdRoute = PerfilUserIdRouteImport.update({
  id: '/perfil/$userId',
  path: '/perfil/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/par-q': typeof ParQRoute
  '/progreso': typeof ProgresoRoute
  '/register': typeof RegisterRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/rutina/$dayId': typeof RutinaDayIdRoute
  '/rutina/': typeof RutinaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/par-q': typeof ParQRoute
  '/progreso': typeof ProgresoRoute
  '/register': typeof RegisterRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/rutina/$dayId': typeof RutinaDayIdRoute
  '/rutina': typeof RutinaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/par-q': typeof ParQRoute
  '/progreso': typeof ProgresoRoute
  '/register': typeof RegisterRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/rutina/$dayId': typeof RutinaDayIdRoute
  '/rutina/': typeof RutinaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/par-q'
    | '/progreso'
    | '/register'
    | '/perfil/$userId'
    | '/rutina/$dayId'
    | '/rutina/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/par-q'
    | '/progreso'
    | '/register'
    | '/perfil/$userId'
    | '/rutina/$dayId'
    | '/rutina'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/par-q'
    | '/progreso'
    | '/register'
    | '/perfil/$userId'
    | '/rutina/$dayId'
    | '/rutina/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ParQRoute: typeof ParQRoute
  ProgresoRoute: typeof ProgresoRoute
  RegisterRoute: typeof RegisterRoute
  PerfilUserIdRoute: typeof PerfilUserIdRoute
  RutinaDayIdRoute: typeof RutinaDayIdRoute
  RutinaIndexRoute: typeof RutinaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/par-q': {
      id: '/par-q'
      path: '/par-q'
      fullPath: '/par-q'
      preLoaderRoute: typeof ParQRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutina/': {
      id: '/rutina/'
      path: '/rutina'
      fullPath: '/rutina/'
      preLoaderRoute: typeof RutinaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutina/$dayId': {
      id: '/rutina/$dayId'
      path: '/rutina/$dayId'
      fullPath: '/rutina/$dayId'
      preLoaderRoute: typeof RutinaDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$userId': {
      id: '/perfil/$userId'
      path: '/perfil/$userId'
      fullPath: '/perfil/$userId'
      preLoaderRoute: typeof PerfilUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ParQRoute: ParQRoute,
  ProgresoRoute: ProgresoRoute,
  RegisterRoute: RegisterRoute,
  PerfilUserIdRoute: PerfilUserIdRoute,
  RutinaDayIdRoute: RutinaDayIdRoute,
  RutinaIndexRoute: RutinaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
