/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterInfoRouteImport } from './routes/register-info'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as ParQRouteImport } from './routes/par-q'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as RutinaDayIdRouteImport } from './routes/rutina.$dayId'
import { Route as PerfilUserIdRouteImport } from './routes/perfil.$userId'
import { Route as ClientesStudentIdRouteImport } from './routes/clientes.$studentId'
import { Route as RutinaStudentIdIndexRouteImport } from './routes/rutina.$studentId.index'

const RegisterInfoRoute = RegisterInfoRouteImport.update({
  id: '/register-info',
  path: '/register-info',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const ParQRoute = ParQRouteImport.update({
  id: '/par-q',
  path: '/par-q',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RutinaDayIdRoute = RutinaDayIdRouteImport.update({
  id: '/rutina/$dayId',
  path: '/rutina/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilUserIdRoute = PerfilUserIdRouteImport.update({
  id: '/perfil/$userId',
  path: '/perfil/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesStudentIdRoute = ClientesStudentIdRouteImport.update({
  id: '/clientes/$studentId',
  path: '/clientes/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const RutinaStudentIdIndexRoute = RutinaStudentIdIndexRouteImport.update({
  id: '/rutina/$studentId/',
  path: '/rutina/$studentId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/par-q': typeof ParQRoute
  '/progreso': typeof ProgresoRoute
  '/register': typeof RegisterRoute
  '/register-info': typeof RegisterInfoRoute
  '/clientes/$studentId': typeof ClientesStudentIdRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/rutina/$dayId': typeof RutinaDayIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/rutina/$studentId/': typeof RutinaStudentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/par-q': typeof ParQRoute
  '/progreso': typeof ProgresoRoute
  '/register': typeof RegisterRoute
  '/register-info': typeof RegisterInfoRoute
  '/clientes/$studentId': typeof ClientesStudentIdRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/rutina/$dayId': typeof RutinaDayIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/rutina/$studentId': typeof RutinaStudentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/par-q': typeof ParQRoute
  '/progreso': typeof ProgresoRoute
  '/register': typeof RegisterRoute
  '/register-info': typeof RegisterInfoRoute
  '/clientes/$studentId': typeof ClientesStudentIdRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/rutina/$dayId': typeof RutinaDayIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/rutina/$studentId/': typeof RutinaStudentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/par-q'
    | '/progreso'
    | '/register'
    | '/register-info'
    | '/clientes/$studentId'
    | '/perfil/$userId'
    | '/rutina/$dayId'
    | '/clientes/'
    | '/rutina/$studentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/par-q'
    | '/progreso'
    | '/register'
    | '/register-info'
    | '/clientes/$studentId'
    | '/perfil/$userId'
    | '/rutina/$dayId'
    | '/clientes'
    | '/rutina/$studentId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/par-q'
    | '/progreso'
    | '/register'
    | '/register-info'
    | '/clientes/$studentId'
    | '/perfil/$userId'
    | '/rutina/$dayId'
    | '/clientes/'
    | '/rutina/$studentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ParQRoute: typeof ParQRoute
  ProgresoRoute: typeof ProgresoRoute
  RegisterRoute: typeof RegisterRoute
  RegisterInfoRoute: typeof RegisterInfoRoute
  ClientesStudentIdRoute: typeof ClientesStudentIdRoute
  PerfilUserIdRoute: typeof PerfilUserIdRoute
  RutinaDayIdRoute: typeof RutinaDayIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  RutinaStudentIdIndexRoute: typeof RutinaStudentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-info': {
      id: '/register-info'
      path: '/register-info'
      fullPath: '/register-info'
      preLoaderRoute: typeof RegisterInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/par-q': {
      id: '/par-q'
      path: '/par-q'
      fullPath: '/par-q'
      preLoaderRoute: typeof ParQRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutina/$dayId': {
      id: '/rutina/$dayId'
      path: '/rutina/$dayId'
      fullPath: '/rutina/$dayId'
      preLoaderRoute: typeof RutinaDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$userId': {
      id: '/perfil/$userId'
      path: '/perfil/$userId'
      fullPath: '/perfil/$userId'
      preLoaderRoute: typeof PerfilUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$studentId': {
      id: '/clientes/$studentId'
      path: '/clientes/$studentId'
      fullPath: '/clientes/$studentId'
      preLoaderRoute: typeof ClientesStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutina/$studentId/': {
      id: '/rutina/$studentId/'
      path: '/rutina/$studentId'
      fullPath: '/rutina/$studentId/'
      preLoaderRoute: typeof RutinaStudentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ParQRoute: ParQRoute,
  ProgresoRoute: ProgresoRoute,
  RegisterRoute: RegisterRoute,
  RegisterInfoRoute: RegisterInfoRoute,
  ClientesStudentIdRoute: ClientesStudentIdRoute,
  PerfilUserIdRoute: PerfilUserIdRoute,
  RutinaDayIdRoute: RutinaDayIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  RutinaStudentIdIndexRoute: RutinaStudentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
